openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: My API Description

paths:
  /api/example:
    get:
      summary: Example API endpoint
      responses:
        "200":
          description: Success response